import { AboutSlint, VerticalBox } from "std-widgets.slint";
import { TopBar } from "top-bar.slint";
import { StartScreen } from "../src/presentation/start/start-screen.slint";
import {
    NameInputScreen,
} from "../src/presentation/name_input/name-input-screen.slint";
import {
    DifficulitySelectScreen,
} from "../src/presentation/difficulity_select/difficulity-select-screen.slint";
import { PlayingScreen } from "playing-screen.slint";
import { ScoreScreen } from "score-screen.slint";
import { RankingScreen } from "ranking-screen.slint";

export {
    StartScreenAdopter,
}from "../src/presentation/start//start-screen.slint";
export {
    NameInputAdopter,
}from "../src/presentation/name_input/name-input-screen.slint";

enum NavRoute {
    Start,
    NameInput,
    DifficulitySelect,
    Playing,
    Score,
    Ranking,
}

export component AppWindow inherits Window {
    full-screen: true;

    in property <NavRoute> nav-route;

    //VerticalLayout {
        top-bar := TopBar { }

    Rectangle {
        y: top-bar.height;

        if nav-route == NavRoute.Start: StartScreen { }
        if nav-route == NavRoute.NameInput: NameInputScreen { }
        if nav-route == NavRoute.DifficulitySelect:DifficulitySelectScreen { }
        if nav-route == NavRoute.Playing: PlayingScreen { }
        if nav-route == NavRoute.Score: ScoreScreen { }
        if nav-route == NavRoute.Ranking: RankingScreen { }
    }
    //}
}
