import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

component Target {
    in property <int> point:100;
    in property <color> color:red;

    Rectangle {
        background: color;
        width: root.width;
        height: root.height;
    }

    Text {
        text: point;
        x: root.x + root.width / 2;
        y: root.y + root.height / 2;
    }
}

export component AppWindow inherits Window {
    in-out property <int> counter: 42;
    callback request-increase-value();
    VerticalBox {
        HorizontalBox {
            Target {
                point: 500;
                color: red;
            }

            Target {
                point: 600;
                color: green;
            }

            Target {
                point: 350;
                color: blue;
            }
        }

        HorizontalBox {
            Target {
                point: 280;
                color: orange;
            }

            Target {
                point: 700;
                color: antiquewhite;
            }

            Target {
                point: 500;
                color: brown;
            }
        }

        HorizontalBox {
            Target {
                point: 500;
                color: red;
            }

            Target {
                point: 600;
                color: green;
            }

            Target {
                point: 350;
                color: blue;
            }
        }
    }
}
