//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: struckout.proto

package struckout;

@kotlin.jvm.JvmName("-initializedetectedObject")
public inline fun detectedObject(block: struckout.DetectedObjectKt.Dsl.() -> kotlin.Unit): struckout.Struckout.DetectedObject =
  struckout.DetectedObjectKt.Dsl._create(struckout.Struckout.DetectedObject.newBuilder()).apply { block() }._build()
public object DetectedObjectKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: struckout.Struckout.DetectedObject.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: struckout.Struckout.DetectedObject.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): struckout.Struckout.DetectedObject = _builder.build()

    /**
     * <code>float bbox_width = 1;</code>
     */
    public var bboxWidth: kotlin.Float
      @JvmName("getBboxWidth")
      get() = _builder.getBboxWidth()
      @JvmName("setBboxWidth")
      set(value) {
        _builder.setBboxWidth(value)
      }
    /**
     * <code>float bbox_width = 1;</code>
     */
    public fun clearBboxWidth() {
      _builder.clearBboxWidth()
    }

    /**
     * <code>float bbox_height = 2;</code>
     */
    public var bboxHeight: kotlin.Float
      @JvmName("getBboxHeight")
      get() = _builder.getBboxHeight()
      @JvmName("setBboxHeight")
      set(value) {
        _builder.setBboxHeight(value)
      }
    /**
     * <code>float bbox_height = 2;</code>
     */
    public fun clearBboxHeight() {
      _builder.clearBboxHeight()
    }

    /**
     * <code>float lay_x = 3;</code>
     */
    public var layX: kotlin.Float
      @JvmName("getLayX")
      get() = _builder.getLayX()
      @JvmName("setLayX")
      set(value) {
        _builder.setLayX(value)
      }
    /**
     * <code>float lay_x = 3;</code>
     */
    public fun clearLayX() {
      _builder.clearLayX()
    }

    /**
     * <code>float lay_y = 4;</code>
     */
    public var layY: kotlin.Float
      @JvmName("getLayY")
      get() = _builder.getLayY()
      @JvmName("setLayY")
      set(value) {
        _builder.setLayY(value)
      }
    /**
     * <code>float lay_y = 4;</code>
     */
    public fun clearLayY() {
      _builder.clearLayY()
    }

    /**
     * <pre>
     * TODO: 特徴量
     * </pre>
     *
     * <code>float lay_z = 5;</code>
     */
    public var layZ: kotlin.Float
      @JvmName("getLayZ")
      get() = _builder.getLayZ()
      @JvmName("setLayZ")
      set(value) {
        _builder.setLayZ(value)
      }
    /**
     * <pre>
     * TODO: 特徴量
     * </pre>
     *
     * <code>float lay_z = 5;</code>
     */
    public fun clearLayZ() {
      _builder.clearLayZ()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun struckout.Struckout.DetectedObject.copy(block: struckout.DetectedObjectKt.Dsl.() -> kotlin.Unit): struckout.Struckout.DetectedObject =
  struckout.DetectedObjectKt.Dsl._create(this.toBuilder()).apply { block() }._build()

