// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: struckout.proto

package struckout;

public final class Struckout {
  private Struckout() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UdpPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:struckout.UdpPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 camera_id = 1;</code>
     * @return The cameraId.
     */
    int getCameraId();

    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     * @return The timestamp.
     */
    com.google.protobuf.Timestamp getTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

    /**
     * <code>uint64 frame_id = 3;</code>
     * @return The frameId.
     */
    long getFrameId();

    /**
     * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
     */
    java.util.List<struckout.Struckout.DetectedObject> 
        getDetectedObjectsList();
    /**
     * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
     */
    struckout.Struckout.DetectedObject getDetectedObjects(int index);
    /**
     * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
     */
    int getDetectedObjectsCount();
    /**
     * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
     */
    java.util.List<? extends struckout.Struckout.DetectedObjectOrBuilder> 
        getDetectedObjectsOrBuilderList();
    /**
     * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
     */
    struckout.Struckout.DetectedObjectOrBuilder getDetectedObjectsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * UDPでカメラからサーバに送られるパケット
   * </pre>
   *
   * Protobuf type {@code struckout.UdpPacket}
   */
  public static final class UdpPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:struckout.UdpPacket)
      UdpPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UdpPacket.newBuilder() to construct.
    private UdpPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UdpPacket() {
      detectedObjects_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UdpPacket();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return struckout.Struckout.internal_static_struckout_UdpPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return struckout.Struckout.internal_static_struckout_UdpPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              struckout.Struckout.UdpPacket.class, struckout.Struckout.UdpPacket.Builder.class);
    }

    public static final int CAMERA_ID_FIELD_NUMBER = 1;
    private int cameraId_ = 0;
    /**
     * <code>uint32 camera_id = 1;</code>
     * @return The cameraId.
     */
    @java.lang.Override
    public int getCameraId() {
      return cameraId_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp timestamp_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return timestamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTimestamp() {
      return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }

    public static final int FRAME_ID_FIELD_NUMBER = 3;
    private long frameId_ = 0L;
    /**
     * <code>uint64 frame_id = 3;</code>
     * @return The frameId.
     */
    @java.lang.Override
    public long getFrameId() {
      return frameId_;
    }

    public static final int DETECTED_OBJECTS_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private java.util.List<struckout.Struckout.DetectedObject> detectedObjects_;
    /**
     * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
     */
    @java.lang.Override
    public java.util.List<struckout.Struckout.DetectedObject> getDetectedObjectsList() {
      return detectedObjects_;
    }
    /**
     * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends struckout.Struckout.DetectedObjectOrBuilder> 
        getDetectedObjectsOrBuilderList() {
      return detectedObjects_;
    }
    /**
     * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
     */
    @java.lang.Override
    public int getDetectedObjectsCount() {
      return detectedObjects_.size();
    }
    /**
     * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
     */
    @java.lang.Override
    public struckout.Struckout.DetectedObject getDetectedObjects(int index) {
      return detectedObjects_.get(index);
    }
    /**
     * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
     */
    @java.lang.Override
    public struckout.Struckout.DetectedObjectOrBuilder getDetectedObjectsOrBuilder(
        int index) {
      return detectedObjects_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cameraId_ != 0) {
        output.writeUInt32(1, cameraId_);
      }
      if (timestamp_ != null) {
        output.writeMessage(2, getTimestamp());
      }
      if (frameId_ != 0L) {
        output.writeUInt64(3, frameId_);
      }
      for (int i = 0; i < detectedObjects_.size(); i++) {
        output.writeMessage(4, detectedObjects_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cameraId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, cameraId_);
      }
      if (timestamp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTimestamp());
      }
      if (frameId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, frameId_);
      }
      for (int i = 0; i < detectedObjects_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, detectedObjects_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof struckout.Struckout.UdpPacket)) {
        return super.equals(obj);
      }
      struckout.Struckout.UdpPacket other = (struckout.Struckout.UdpPacket) obj;

      if (getCameraId()
          != other.getCameraId()) return false;
      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (!getTimestamp()
            .equals(other.getTimestamp())) return false;
      }
      if (getFrameId()
          != other.getFrameId()) return false;
      if (!getDetectedObjectsList()
          .equals(other.getDetectedObjectsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CAMERA_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCameraId();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      hash = (37 * hash) + FRAME_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFrameId());
      if (getDetectedObjectsCount() > 0) {
        hash = (37 * hash) + DETECTED_OBJECTS_FIELD_NUMBER;
        hash = (53 * hash) + getDetectedObjectsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static struckout.Struckout.UdpPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static struckout.Struckout.UdpPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static struckout.Struckout.UdpPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static struckout.Struckout.UdpPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static struckout.Struckout.UdpPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static struckout.Struckout.UdpPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static struckout.Struckout.UdpPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static struckout.Struckout.UdpPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static struckout.Struckout.UdpPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static struckout.Struckout.UdpPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static struckout.Struckout.UdpPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static struckout.Struckout.UdpPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(struckout.Struckout.UdpPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * UDPでカメラからサーバに送られるパケット
     * </pre>
     *
     * Protobuf type {@code struckout.UdpPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:struckout.UdpPacket)
        struckout.Struckout.UdpPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return struckout.Struckout.internal_static_struckout_UdpPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return struckout.Struckout.internal_static_struckout_UdpPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                struckout.Struckout.UdpPacket.class, struckout.Struckout.UdpPacket.Builder.class);
      }

      // Construct using struckout.Struckout.UdpPacket.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        cameraId_ = 0;
        timestamp_ = null;
        if (timestampBuilder_ != null) {
          timestampBuilder_.dispose();
          timestampBuilder_ = null;
        }
        frameId_ = 0L;
        if (detectedObjectsBuilder_ == null) {
          detectedObjects_ = java.util.Collections.emptyList();
        } else {
          detectedObjects_ = null;
          detectedObjectsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return struckout.Struckout.internal_static_struckout_UdpPacket_descriptor;
      }

      @java.lang.Override
      public struckout.Struckout.UdpPacket getDefaultInstanceForType() {
        return struckout.Struckout.UdpPacket.getDefaultInstance();
      }

      @java.lang.Override
      public struckout.Struckout.UdpPacket build() {
        struckout.Struckout.UdpPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public struckout.Struckout.UdpPacket buildPartial() {
        struckout.Struckout.UdpPacket result = new struckout.Struckout.UdpPacket(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(struckout.Struckout.UdpPacket result) {
        if (detectedObjectsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0)) {
            detectedObjects_ = java.util.Collections.unmodifiableList(detectedObjects_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.detectedObjects_ = detectedObjects_;
        } else {
          result.detectedObjects_ = detectedObjectsBuilder_.build();
        }
      }

      private void buildPartial0(struckout.Struckout.UdpPacket result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.cameraId_ = cameraId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.timestamp_ = timestampBuilder_ == null
              ? timestamp_
              : timestampBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.frameId_ = frameId_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof struckout.Struckout.UdpPacket) {
          return mergeFrom((struckout.Struckout.UdpPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(struckout.Struckout.UdpPacket other) {
        if (other == struckout.Struckout.UdpPacket.getDefaultInstance()) return this;
        if (other.getCameraId() != 0) {
          setCameraId(other.getCameraId());
        }
        if (other.hasTimestamp()) {
          mergeTimestamp(other.getTimestamp());
        }
        if (other.getFrameId() != 0L) {
          setFrameId(other.getFrameId());
        }
        if (detectedObjectsBuilder_ == null) {
          if (!other.detectedObjects_.isEmpty()) {
            if (detectedObjects_.isEmpty()) {
              detectedObjects_ = other.detectedObjects_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureDetectedObjectsIsMutable();
              detectedObjects_.addAll(other.detectedObjects_);
            }
            onChanged();
          }
        } else {
          if (!other.detectedObjects_.isEmpty()) {
            if (detectedObjectsBuilder_.isEmpty()) {
              detectedObjectsBuilder_.dispose();
              detectedObjectsBuilder_ = null;
              detectedObjects_ = other.detectedObjects_;
              bitField0_ = (bitField0_ & ~0x00000008);
              detectedObjectsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDetectedObjectsFieldBuilder() : null;
            } else {
              detectedObjectsBuilder_.addAllMessages(other.detectedObjects_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                cameraId_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getTimestampFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                frameId_ = input.readUInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                struckout.Struckout.DetectedObject m =
                    input.readMessage(
                        struckout.Struckout.DetectedObject.parser(),
                        extensionRegistry);
                if (detectedObjectsBuilder_ == null) {
                  ensureDetectedObjectsIsMutable();
                  detectedObjects_.add(m);
                } else {
                  detectedObjectsBuilder_.addMessage(m);
                }
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int cameraId_ ;
      /**
       * <code>uint32 camera_id = 1;</code>
       * @return The cameraId.
       */
      @java.lang.Override
      public int getCameraId() {
        return cameraId_;
      }
      /**
       * <code>uint32 camera_id = 1;</code>
       * @param value The cameraId to set.
       * @return This builder for chaining.
       */
      public Builder setCameraId(int value) {
        
        cameraId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 camera_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCameraId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cameraId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp timestamp_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       * @return Whether the timestamp field is set.
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       * @return The timestamp.
       */
      public com.google.protobuf.Timestamp getTimestamp() {
        if (timestampBuilder_ == null) {
          return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        } else {
          return timestampBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       */
      public Builder setTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timestamp_ = value;
        } else {
          timestampBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       */
      public Builder setTimestamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timestampBuilder_ == null) {
          timestamp_ = builderForValue.build();
        } else {
          timestampBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       */
      public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            timestamp_ != null &&
            timestamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getTimestampBuilder().mergeFrom(value);
          } else {
            timestamp_ = value;
          }
        } else {
          timestampBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = null;
        if (timestampBuilder_ != null) {
          timestampBuilder_.dispose();
          timestampBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getTimestampFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
        if (timestampBuilder_ != null) {
          return timestampBuilder_.getMessageOrBuilder();
        } else {
          return timestamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTimestampFieldBuilder() {
        if (timestampBuilder_ == null) {
          timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTimestamp(),
                  getParentForChildren(),
                  isClean());
          timestamp_ = null;
        }
        return timestampBuilder_;
      }

      private long frameId_ ;
      /**
       * <code>uint64 frame_id = 3;</code>
       * @return The frameId.
       */
      @java.lang.Override
      public long getFrameId() {
        return frameId_;
      }
      /**
       * <code>uint64 frame_id = 3;</code>
       * @param value The frameId to set.
       * @return This builder for chaining.
       */
      public Builder setFrameId(long value) {
        
        frameId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 frame_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFrameId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        frameId_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<struckout.Struckout.DetectedObject> detectedObjects_ =
        java.util.Collections.emptyList();
      private void ensureDetectedObjectsIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          detectedObjects_ = new java.util.ArrayList<struckout.Struckout.DetectedObject>(detectedObjects_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          struckout.Struckout.DetectedObject, struckout.Struckout.DetectedObject.Builder, struckout.Struckout.DetectedObjectOrBuilder> detectedObjectsBuilder_;

      /**
       * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
       */
      public java.util.List<struckout.Struckout.DetectedObject> getDetectedObjectsList() {
        if (detectedObjectsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(detectedObjects_);
        } else {
          return detectedObjectsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
       */
      public int getDetectedObjectsCount() {
        if (detectedObjectsBuilder_ == null) {
          return detectedObjects_.size();
        } else {
          return detectedObjectsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
       */
      public struckout.Struckout.DetectedObject getDetectedObjects(int index) {
        if (detectedObjectsBuilder_ == null) {
          return detectedObjects_.get(index);
        } else {
          return detectedObjectsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
       */
      public Builder setDetectedObjects(
          int index, struckout.Struckout.DetectedObject value) {
        if (detectedObjectsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDetectedObjectsIsMutable();
          detectedObjects_.set(index, value);
          onChanged();
        } else {
          detectedObjectsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
       */
      public Builder setDetectedObjects(
          int index, struckout.Struckout.DetectedObject.Builder builderForValue) {
        if (detectedObjectsBuilder_ == null) {
          ensureDetectedObjectsIsMutable();
          detectedObjects_.set(index, builderForValue.build());
          onChanged();
        } else {
          detectedObjectsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
       */
      public Builder addDetectedObjects(struckout.Struckout.DetectedObject value) {
        if (detectedObjectsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDetectedObjectsIsMutable();
          detectedObjects_.add(value);
          onChanged();
        } else {
          detectedObjectsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
       */
      public Builder addDetectedObjects(
          int index, struckout.Struckout.DetectedObject value) {
        if (detectedObjectsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDetectedObjectsIsMutable();
          detectedObjects_.add(index, value);
          onChanged();
        } else {
          detectedObjectsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
       */
      public Builder addDetectedObjects(
          struckout.Struckout.DetectedObject.Builder builderForValue) {
        if (detectedObjectsBuilder_ == null) {
          ensureDetectedObjectsIsMutable();
          detectedObjects_.add(builderForValue.build());
          onChanged();
        } else {
          detectedObjectsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
       */
      public Builder addDetectedObjects(
          int index, struckout.Struckout.DetectedObject.Builder builderForValue) {
        if (detectedObjectsBuilder_ == null) {
          ensureDetectedObjectsIsMutable();
          detectedObjects_.add(index, builderForValue.build());
          onChanged();
        } else {
          detectedObjectsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
       */
      public Builder addAllDetectedObjects(
          java.lang.Iterable<? extends struckout.Struckout.DetectedObject> values) {
        if (detectedObjectsBuilder_ == null) {
          ensureDetectedObjectsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, detectedObjects_);
          onChanged();
        } else {
          detectedObjectsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
       */
      public Builder clearDetectedObjects() {
        if (detectedObjectsBuilder_ == null) {
          detectedObjects_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          detectedObjectsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
       */
      public Builder removeDetectedObjects(int index) {
        if (detectedObjectsBuilder_ == null) {
          ensureDetectedObjectsIsMutable();
          detectedObjects_.remove(index);
          onChanged();
        } else {
          detectedObjectsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
       */
      public struckout.Struckout.DetectedObject.Builder getDetectedObjectsBuilder(
          int index) {
        return getDetectedObjectsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
       */
      public struckout.Struckout.DetectedObjectOrBuilder getDetectedObjectsOrBuilder(
          int index) {
        if (detectedObjectsBuilder_ == null) {
          return detectedObjects_.get(index);  } else {
          return detectedObjectsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
       */
      public java.util.List<? extends struckout.Struckout.DetectedObjectOrBuilder> 
           getDetectedObjectsOrBuilderList() {
        if (detectedObjectsBuilder_ != null) {
          return detectedObjectsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(detectedObjects_);
        }
      }
      /**
       * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
       */
      public struckout.Struckout.DetectedObject.Builder addDetectedObjectsBuilder() {
        return getDetectedObjectsFieldBuilder().addBuilder(
            struckout.Struckout.DetectedObject.getDefaultInstance());
      }
      /**
       * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
       */
      public struckout.Struckout.DetectedObject.Builder addDetectedObjectsBuilder(
          int index) {
        return getDetectedObjectsFieldBuilder().addBuilder(
            index, struckout.Struckout.DetectedObject.getDefaultInstance());
      }
      /**
       * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
       */
      public java.util.List<struckout.Struckout.DetectedObject.Builder> 
           getDetectedObjectsBuilderList() {
        return getDetectedObjectsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          struckout.Struckout.DetectedObject, struckout.Struckout.DetectedObject.Builder, struckout.Struckout.DetectedObjectOrBuilder> 
          getDetectedObjectsFieldBuilder() {
        if (detectedObjectsBuilder_ == null) {
          detectedObjectsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              struckout.Struckout.DetectedObject, struckout.Struckout.DetectedObject.Builder, struckout.Struckout.DetectedObjectOrBuilder>(
                  detectedObjects_,
                  ((bitField0_ & 0x00000008) != 0),
                  getParentForChildren(),
                  isClean());
          detectedObjects_ = null;
        }
        return detectedObjectsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:struckout.UdpPacket)
    }

    // @@protoc_insertion_point(class_scope:struckout.UdpPacket)
    private static final struckout.Struckout.UdpPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new struckout.Struckout.UdpPacket();
    }

    public static struckout.Struckout.UdpPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UdpPacket>
        PARSER = new com.google.protobuf.AbstractParser<UdpPacket>() {
      @java.lang.Override
      public UdpPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UdpPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UdpPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public struckout.Struckout.UdpPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DetectedObjectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:struckout.DetectedObject)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float bbox_width = 1;</code>
     * @return The bboxWidth.
     */
    float getBboxWidth();

    /**
     * <code>float bbox_height = 2;</code>
     * @return The bboxHeight.
     */
    float getBboxHeight();

    /**
     * <code>float lay_x = 3;</code>
     * @return The layX.
     */
    float getLayX();

    /**
     * <code>float lay_y = 4;</code>
     * @return The layY.
     */
    float getLayY();

    /**
     * <pre>
     * TODO: 特徴量
     * </pre>
     *
     * <code>float lay_z = 5;</code>
     * @return The layZ.
     */
    float getLayZ();
  }
  /**
   * Protobuf type {@code struckout.DetectedObject}
   */
  public static final class DetectedObject extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:struckout.DetectedObject)
      DetectedObjectOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DetectedObject.newBuilder() to construct.
    private DetectedObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DetectedObject() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DetectedObject();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return struckout.Struckout.internal_static_struckout_DetectedObject_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return struckout.Struckout.internal_static_struckout_DetectedObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              struckout.Struckout.DetectedObject.class, struckout.Struckout.DetectedObject.Builder.class);
    }

    public static final int BBOX_WIDTH_FIELD_NUMBER = 1;
    private float bboxWidth_ = 0F;
    /**
     * <code>float bbox_width = 1;</code>
     * @return The bboxWidth.
     */
    @java.lang.Override
    public float getBboxWidth() {
      return bboxWidth_;
    }

    public static final int BBOX_HEIGHT_FIELD_NUMBER = 2;
    private float bboxHeight_ = 0F;
    /**
     * <code>float bbox_height = 2;</code>
     * @return The bboxHeight.
     */
    @java.lang.Override
    public float getBboxHeight() {
      return bboxHeight_;
    }

    public static final int LAY_X_FIELD_NUMBER = 3;
    private float layX_ = 0F;
    /**
     * <code>float lay_x = 3;</code>
     * @return The layX.
     */
    @java.lang.Override
    public float getLayX() {
      return layX_;
    }

    public static final int LAY_Y_FIELD_NUMBER = 4;
    private float layY_ = 0F;
    /**
     * <code>float lay_y = 4;</code>
     * @return The layY.
     */
    @java.lang.Override
    public float getLayY() {
      return layY_;
    }

    public static final int LAY_Z_FIELD_NUMBER = 5;
    private float layZ_ = 0F;
    /**
     * <pre>
     * TODO: 特徴量
     * </pre>
     *
     * <code>float lay_z = 5;</code>
     * @return The layZ.
     */
    @java.lang.Override
    public float getLayZ() {
      return layZ_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Float.floatToRawIntBits(bboxWidth_) != 0) {
        output.writeFloat(1, bboxWidth_);
      }
      if (java.lang.Float.floatToRawIntBits(bboxHeight_) != 0) {
        output.writeFloat(2, bboxHeight_);
      }
      if (java.lang.Float.floatToRawIntBits(layX_) != 0) {
        output.writeFloat(3, layX_);
      }
      if (java.lang.Float.floatToRawIntBits(layY_) != 0) {
        output.writeFloat(4, layY_);
      }
      if (java.lang.Float.floatToRawIntBits(layZ_) != 0) {
        output.writeFloat(5, layZ_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Float.floatToRawIntBits(bboxWidth_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, bboxWidth_);
      }
      if (java.lang.Float.floatToRawIntBits(bboxHeight_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, bboxHeight_);
      }
      if (java.lang.Float.floatToRawIntBits(layX_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, layX_);
      }
      if (java.lang.Float.floatToRawIntBits(layY_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, layY_);
      }
      if (java.lang.Float.floatToRawIntBits(layZ_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, layZ_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof struckout.Struckout.DetectedObject)) {
        return super.equals(obj);
      }
      struckout.Struckout.DetectedObject other = (struckout.Struckout.DetectedObject) obj;

      if (java.lang.Float.floatToIntBits(getBboxWidth())
          != java.lang.Float.floatToIntBits(
              other.getBboxWidth())) return false;
      if (java.lang.Float.floatToIntBits(getBboxHeight())
          != java.lang.Float.floatToIntBits(
              other.getBboxHeight())) return false;
      if (java.lang.Float.floatToIntBits(getLayX())
          != java.lang.Float.floatToIntBits(
              other.getLayX())) return false;
      if (java.lang.Float.floatToIntBits(getLayY())
          != java.lang.Float.floatToIntBits(
              other.getLayY())) return false;
      if (java.lang.Float.floatToIntBits(getLayZ())
          != java.lang.Float.floatToIntBits(
              other.getLayZ())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BBOX_WIDTH_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getBboxWidth());
      hash = (37 * hash) + BBOX_HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getBboxHeight());
      hash = (37 * hash) + LAY_X_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLayX());
      hash = (37 * hash) + LAY_Y_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLayY());
      hash = (37 * hash) + LAY_Z_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLayZ());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static struckout.Struckout.DetectedObject parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static struckout.Struckout.DetectedObject parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static struckout.Struckout.DetectedObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static struckout.Struckout.DetectedObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static struckout.Struckout.DetectedObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static struckout.Struckout.DetectedObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static struckout.Struckout.DetectedObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static struckout.Struckout.DetectedObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static struckout.Struckout.DetectedObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static struckout.Struckout.DetectedObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static struckout.Struckout.DetectedObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static struckout.Struckout.DetectedObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(struckout.Struckout.DetectedObject prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code struckout.DetectedObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:struckout.DetectedObject)
        struckout.Struckout.DetectedObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return struckout.Struckout.internal_static_struckout_DetectedObject_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return struckout.Struckout.internal_static_struckout_DetectedObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                struckout.Struckout.DetectedObject.class, struckout.Struckout.DetectedObject.Builder.class);
      }

      // Construct using struckout.Struckout.DetectedObject.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        bboxWidth_ = 0F;
        bboxHeight_ = 0F;
        layX_ = 0F;
        layY_ = 0F;
        layZ_ = 0F;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return struckout.Struckout.internal_static_struckout_DetectedObject_descriptor;
      }

      @java.lang.Override
      public struckout.Struckout.DetectedObject getDefaultInstanceForType() {
        return struckout.Struckout.DetectedObject.getDefaultInstance();
      }

      @java.lang.Override
      public struckout.Struckout.DetectedObject build() {
        struckout.Struckout.DetectedObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public struckout.Struckout.DetectedObject buildPartial() {
        struckout.Struckout.DetectedObject result = new struckout.Struckout.DetectedObject(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(struckout.Struckout.DetectedObject result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.bboxWidth_ = bboxWidth_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.bboxHeight_ = bboxHeight_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.layX_ = layX_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.layY_ = layY_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.layZ_ = layZ_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof struckout.Struckout.DetectedObject) {
          return mergeFrom((struckout.Struckout.DetectedObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(struckout.Struckout.DetectedObject other) {
        if (other == struckout.Struckout.DetectedObject.getDefaultInstance()) return this;
        if (other.getBboxWidth() != 0F) {
          setBboxWidth(other.getBboxWidth());
        }
        if (other.getBboxHeight() != 0F) {
          setBboxHeight(other.getBboxHeight());
        }
        if (other.getLayX() != 0F) {
          setLayX(other.getLayX());
        }
        if (other.getLayY() != 0F) {
          setLayY(other.getLayY());
        }
        if (other.getLayZ() != 0F) {
          setLayZ(other.getLayZ());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                bboxWidth_ = input.readFloat();
                bitField0_ |= 0x00000001;
                break;
              } // case 13
              case 21: {
                bboxHeight_ = input.readFloat();
                bitField0_ |= 0x00000002;
                break;
              } // case 21
              case 29: {
                layX_ = input.readFloat();
                bitField0_ |= 0x00000004;
                break;
              } // case 29
              case 37: {
                layY_ = input.readFloat();
                bitField0_ |= 0x00000008;
                break;
              } // case 37
              case 45: {
                layZ_ = input.readFloat();
                bitField0_ |= 0x00000010;
                break;
              } // case 45
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private float bboxWidth_ ;
      /**
       * <code>float bbox_width = 1;</code>
       * @return The bboxWidth.
       */
      @java.lang.Override
      public float getBboxWidth() {
        return bboxWidth_;
      }
      /**
       * <code>float bbox_width = 1;</code>
       * @param value The bboxWidth to set.
       * @return This builder for chaining.
       */
      public Builder setBboxWidth(float value) {
        
        bboxWidth_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>float bbox_width = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBboxWidth() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bboxWidth_ = 0F;
        onChanged();
        return this;
      }

      private float bboxHeight_ ;
      /**
       * <code>float bbox_height = 2;</code>
       * @return The bboxHeight.
       */
      @java.lang.Override
      public float getBboxHeight() {
        return bboxHeight_;
      }
      /**
       * <code>float bbox_height = 2;</code>
       * @param value The bboxHeight to set.
       * @return This builder for chaining.
       */
      public Builder setBboxHeight(float value) {
        
        bboxHeight_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>float bbox_height = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBboxHeight() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bboxHeight_ = 0F;
        onChanged();
        return this;
      }

      private float layX_ ;
      /**
       * <code>float lay_x = 3;</code>
       * @return The layX.
       */
      @java.lang.Override
      public float getLayX() {
        return layX_;
      }
      /**
       * <code>float lay_x = 3;</code>
       * @param value The layX to set.
       * @return This builder for chaining.
       */
      public Builder setLayX(float value) {
        
        layX_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>float lay_x = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLayX() {
        bitField0_ = (bitField0_ & ~0x00000004);
        layX_ = 0F;
        onChanged();
        return this;
      }

      private float layY_ ;
      /**
       * <code>float lay_y = 4;</code>
       * @return The layY.
       */
      @java.lang.Override
      public float getLayY() {
        return layY_;
      }
      /**
       * <code>float lay_y = 4;</code>
       * @param value The layY to set.
       * @return This builder for chaining.
       */
      public Builder setLayY(float value) {
        
        layY_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>float lay_y = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLayY() {
        bitField0_ = (bitField0_ & ~0x00000008);
        layY_ = 0F;
        onChanged();
        return this;
      }

      private float layZ_ ;
      /**
       * <pre>
       * TODO: 特徴量
       * </pre>
       *
       * <code>float lay_z = 5;</code>
       * @return The layZ.
       */
      @java.lang.Override
      public float getLayZ() {
        return layZ_;
      }
      /**
       * <pre>
       * TODO: 特徴量
       * </pre>
       *
       * <code>float lay_z = 5;</code>
       * @param value The layZ to set.
       * @return This builder for chaining.
       */
      public Builder setLayZ(float value) {
        
        layZ_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * TODO: 特徴量
       * </pre>
       *
       * <code>float lay_z = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLayZ() {
        bitField0_ = (bitField0_ & ~0x00000010);
        layZ_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:struckout.DetectedObject)
    }

    // @@protoc_insertion_point(class_scope:struckout.DetectedObject)
    private static final struckout.Struckout.DetectedObject DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new struckout.Struckout.DetectedObject();
    }

    public static struckout.Struckout.DetectedObject getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DetectedObject>
        PARSER = new com.google.protobuf.AbstractParser<DetectedObject>() {
      @java.lang.Override
      public DetectedObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DetectedObject> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DetectedObject> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public struckout.Struckout.DetectedObject getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TcpPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:struckout.TcpPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float x = 1;</code>
     * @return The x.
     */
    float getX();

    /**
     * <code>float y = 2;</code>
     * @return The y.
     */
    float getY();

    /**
     * <code>float z = 3;</code>
     * @return The z.
     */
    float getZ();
  }
  /**
   * <pre>
   * TCPでカメラからサーバに送られるパケット
   * </pre>
   *
   * Protobuf type {@code struckout.TcpPacket}
   */
  public static final class TcpPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:struckout.TcpPacket)
      TcpPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TcpPacket.newBuilder() to construct.
    private TcpPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TcpPacket() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TcpPacket();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return struckout.Struckout.internal_static_struckout_TcpPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return struckout.Struckout.internal_static_struckout_TcpPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              struckout.Struckout.TcpPacket.class, struckout.Struckout.TcpPacket.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private float x_ = 0F;
    /**
     * <code>float x = 1;</code>
     * @return The x.
     */
    @java.lang.Override
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private float y_ = 0F;
    /**
     * <code>float y = 2;</code>
     * @return The y.
     */
    @java.lang.Override
    public float getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 3;
    private float z_ = 0F;
    /**
     * <code>float z = 3;</code>
     * @return The z.
     */
    @java.lang.Override
    public float getZ() {
      return z_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Float.floatToRawIntBits(x_) != 0) {
        output.writeFloat(1, x_);
      }
      if (java.lang.Float.floatToRawIntBits(y_) != 0) {
        output.writeFloat(2, y_);
      }
      if (java.lang.Float.floatToRawIntBits(z_) != 0) {
        output.writeFloat(3, z_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Float.floatToRawIntBits(x_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, x_);
      }
      if (java.lang.Float.floatToRawIntBits(y_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, y_);
      }
      if (java.lang.Float.floatToRawIntBits(z_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, z_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof struckout.Struckout.TcpPacket)) {
        return super.equals(obj);
      }
      struckout.Struckout.TcpPacket other = (struckout.Struckout.TcpPacket) obj;

      if (java.lang.Float.floatToIntBits(getX())
          != java.lang.Float.floatToIntBits(
              other.getX())) return false;
      if (java.lang.Float.floatToIntBits(getY())
          != java.lang.Float.floatToIntBits(
              other.getY())) return false;
      if (java.lang.Float.floatToIntBits(getZ())
          != java.lang.Float.floatToIntBits(
              other.getZ())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getX());
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getY());
      hash = (37 * hash) + Z_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getZ());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static struckout.Struckout.TcpPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static struckout.Struckout.TcpPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static struckout.Struckout.TcpPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static struckout.Struckout.TcpPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static struckout.Struckout.TcpPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static struckout.Struckout.TcpPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static struckout.Struckout.TcpPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static struckout.Struckout.TcpPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static struckout.Struckout.TcpPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static struckout.Struckout.TcpPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static struckout.Struckout.TcpPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static struckout.Struckout.TcpPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(struckout.Struckout.TcpPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * TCPでカメラからサーバに送られるパケット
     * </pre>
     *
     * Protobuf type {@code struckout.TcpPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:struckout.TcpPacket)
        struckout.Struckout.TcpPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return struckout.Struckout.internal_static_struckout_TcpPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return struckout.Struckout.internal_static_struckout_TcpPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                struckout.Struckout.TcpPacket.class, struckout.Struckout.TcpPacket.Builder.class);
      }

      // Construct using struckout.Struckout.TcpPacket.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        x_ = 0F;
        y_ = 0F;
        z_ = 0F;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return struckout.Struckout.internal_static_struckout_TcpPacket_descriptor;
      }

      @java.lang.Override
      public struckout.Struckout.TcpPacket getDefaultInstanceForType() {
        return struckout.Struckout.TcpPacket.getDefaultInstance();
      }

      @java.lang.Override
      public struckout.Struckout.TcpPacket build() {
        struckout.Struckout.TcpPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public struckout.Struckout.TcpPacket buildPartial() {
        struckout.Struckout.TcpPacket result = new struckout.Struckout.TcpPacket(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(struckout.Struckout.TcpPacket result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.x_ = x_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.y_ = y_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.z_ = z_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof struckout.Struckout.TcpPacket) {
          return mergeFrom((struckout.Struckout.TcpPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(struckout.Struckout.TcpPacket other) {
        if (other == struckout.Struckout.TcpPacket.getDefaultInstance()) return this;
        if (other.getX() != 0F) {
          setX(other.getX());
        }
        if (other.getY() != 0F) {
          setY(other.getY());
        }
        if (other.getZ() != 0F) {
          setZ(other.getZ());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                x_ = input.readFloat();
                bitField0_ |= 0x00000001;
                break;
              } // case 13
              case 21: {
                y_ = input.readFloat();
                bitField0_ |= 0x00000002;
                break;
              } // case 21
              case 29: {
                z_ = input.readFloat();
                bitField0_ |= 0x00000004;
                break;
              } // case 29
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private float x_ ;
      /**
       * <code>float x = 1;</code>
       * @return The x.
       */
      @java.lang.Override
      public float getX() {
        return x_;
      }
      /**
       * <code>float x = 1;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(float value) {
        
        x_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>float x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <code>float y = 2;</code>
       * @return The y.
       */
      @java.lang.Override
      public float getY() {
        return y_;
      }
      /**
       * <code>float y = 2;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(float value) {
        
        y_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>float y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0F;
        onChanged();
        return this;
      }

      private float z_ ;
      /**
       * <code>float z = 3;</code>
       * @return The z.
       */
      @java.lang.Override
      public float getZ() {
        return z_;
      }
      /**
       * <code>float z = 3;</code>
       * @param value The z to set.
       * @return This builder for chaining.
       */
      public Builder setZ(float value) {
        
        z_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>float z = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000004);
        z_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:struckout.TcpPacket)
    }

    // @@protoc_insertion_point(class_scope:struckout.TcpPacket)
    private static final struckout.Struckout.TcpPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new struckout.Struckout.TcpPacket();
    }

    public static struckout.Struckout.TcpPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TcpPacket>
        PARSER = new com.google.protobuf.AbstractParser<TcpPacket>() {
      @java.lang.Override
      public TcpPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TcpPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TcpPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public struckout.Struckout.TcpPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_struckout_UdpPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_struckout_UdpPacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_struckout_DetectedObject_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_struckout_DetectedObject_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_struckout_TcpPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_struckout_TcpPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017struckout.proto\022\tstruckout\032\037google/pro" +
      "tobuf/timestamp.proto\"\224\001\n\tUdpPacket\022\021\n\tc" +
      "amera_id\030\001 \001(\r\022-\n\ttimestamp\030\002 \001(\0132\032.goog" +
      "le.protobuf.Timestamp\022\020\n\010frame_id\030\003 \001(\004\022" +
      "3\n\020detected_objects\030\004 \003(\0132\031.struckout.De" +
      "tectedObject\"f\n\016DetectedObject\022\022\n\nbbox_w" +
      "idth\030\001 \001(\002\022\023\n\013bbox_height\030\002 \001(\002\022\r\n\005lay_x" +
      "\030\003 \001(\002\022\r\n\005lay_y\030\004 \001(\002\022\r\n\005lay_z\030\005 \001(\002\",\n\t" +
      "TcpPacket\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001" +
      "(\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_struckout_UdpPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_struckout_UdpPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_struckout_UdpPacket_descriptor,
        new java.lang.String[] { "CameraId", "Timestamp", "FrameId", "DetectedObjects", });
    internal_static_struckout_DetectedObject_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_struckout_DetectedObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_struckout_DetectedObject_descriptor,
        new java.lang.String[] { "BboxWidth", "BboxHeight", "LayX", "LayY", "LayZ", });
    internal_static_struckout_TcpPacket_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_struckout_TcpPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_struckout_TcpPacket_descriptor,
        new java.lang.String[] { "X", "Y", "Z", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
