//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: struckout.proto

package struckout;

@kotlin.jvm.JvmName("-initializetcpClientPacket")
public inline fun tcpClientPacket(block: struckout.TcpClientPacketKt.Dsl.() -> kotlin.Unit): struckout.Struckout.TcpClientPacket =
  struckout.TcpClientPacketKt.Dsl._create(struckout.Struckout.TcpClientPacket.newBuilder()).apply { block() }._build()
public object TcpClientPacketKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: struckout.Struckout.TcpClientPacket.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: struckout.Struckout.TcpClientPacket.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): struckout.Struckout.TcpClientPacket = _builder.build()

    /**
     * <code>.struckout.CameraLocation camera_location = 1;</code>
     */
    public var cameraLocation: struckout.Struckout.CameraLocation
      @JvmName("getCameraLocation")
      get() = _builder.getCameraLocation()
      @JvmName("setCameraLocation")
      set(value) {
        _builder.setCameraLocation(value)
      }
    /**
     * <code>.struckout.CameraLocation camera_location = 1;</code>
     */
    public fun clearCameraLocation() {
      _builder.clearCameraLocation()
    }
    /**
     * <code>.struckout.CameraLocation camera_location = 1;</code>
     * @return Whether the cameraLocation field is set.
     */
    public fun hasCameraLocation(): kotlin.Boolean {
      return _builder.hasCameraLocation()
    }
    public val dataCase: struckout.Struckout.TcpClientPacket.DataCase
      @JvmName("getDataCase")
      get() = _builder.getDataCase()

    public fun clearData() {
      _builder.clearData()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun struckout.Struckout.TcpClientPacket.copy(block: struckout.TcpClientPacketKt.Dsl.() -> kotlin.Unit): struckout.Struckout.TcpClientPacket =
  struckout.TcpClientPacketKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val struckout.Struckout.TcpClientPacketOrBuilder.cameraLocationOrNull: struckout.Struckout.CameraLocation?
  get() = if (hasCameraLocation()) getCameraLocation() else null

