//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: struckout.proto

package struckout;

@kotlin.jvm.JvmName("-initializetcpPacket")
public inline fun tcpPacket(block: struckout.TcpPacketKt.Dsl.() -> kotlin.Unit): struckout.Struckout.TcpPacket =
  struckout.TcpPacketKt.Dsl._create(struckout.Struckout.TcpPacket.newBuilder()).apply { block() }._build()
public object TcpPacketKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: struckout.Struckout.TcpPacket.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: struckout.Struckout.TcpPacket.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): struckout.Struckout.TcpPacket = _builder.build()

    /**
     * <code>float x = 1;</code>
     */
    public var x: kotlin.Float
      @JvmName("getX")
      get() = _builder.getX()
      @JvmName("setX")
      set(value) {
        _builder.setX(value)
      }
    /**
     * <code>float x = 1;</code>
     */
    public fun clearX() {
      _builder.clearX()
    }

    /**
     * <code>float y = 2;</code>
     */
    public var y: kotlin.Float
      @JvmName("getY")
      get() = _builder.getY()
      @JvmName("setY")
      set(value) {
        _builder.setY(value)
      }
    /**
     * <code>float y = 2;</code>
     */
    public fun clearY() {
      _builder.clearY()
    }

    /**
     * <code>float z = 3;</code>
     */
    public var z: kotlin.Float
      @JvmName("getZ")
      get() = _builder.getZ()
      @JvmName("setZ")
      set(value) {
        _builder.setZ(value)
      }
    /**
     * <code>float z = 3;</code>
     */
    public fun clearZ() {
      _builder.clearZ()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun struckout.Struckout.TcpPacket.copy(block: struckout.TcpPacketKt.Dsl.() -> kotlin.Unit): struckout.Struckout.TcpPacket =
  struckout.TcpPacketKt.Dsl._create(this.toBuilder()).apply { block() }._build()

