//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: struckout.proto

package struckout;

@kotlin.jvm.JvmName("-initializetcpServerPacket")
public inline fun tcpServerPacket(block: struckout.TcpServerPacketKt.Dsl.() -> kotlin.Unit): struckout.Struckout.TcpServerPacket =
  struckout.TcpServerPacketKt.Dsl._create(struckout.Struckout.TcpServerPacket.newBuilder()).apply { block() }._build()
public object TcpServerPacketKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: struckout.Struckout.TcpServerPacket.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: struckout.Struckout.TcpServerPacket.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): struckout.Struckout.TcpServerPacket = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun struckout.Struckout.TcpServerPacket.copy(block: struckout.TcpServerPacketKt.Dsl.() -> kotlin.Unit): struckout.Struckout.TcpServerPacket =
  struckout.TcpServerPacketKt.Dsl._create(this.toBuilder()).apply { block() }._build()

