//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: struckout.proto

package struckout;

@kotlin.jvm.JvmName("-initializeudpPacket")
public inline fun udpPacket(block: struckout.UdpPacketKt.Dsl.() -> kotlin.Unit): struckout.Struckout.UdpPacket =
  struckout.UdpPacketKt.Dsl._create(struckout.Struckout.UdpPacket.newBuilder()).apply { block() }._build()
public object UdpPacketKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: struckout.Struckout.UdpPacket.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: struckout.Struckout.UdpPacket.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): struckout.Struckout.UdpPacket = _builder.build()

    /**
     * <code>uint32 camera_id = 1;</code>
     */
    public var cameraId: kotlin.Int
      @JvmName("getCameraId")
      get() = _builder.getCameraId()
      @JvmName("setCameraId")
      set(value) {
        _builder.setCameraId(value)
      }
    /**
     * <code>uint32 camera_id = 1;</code>
     */
    public fun clearCameraId() {
      _builder.clearCameraId()
    }

    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    public var timestamp: com.google.protobuf.Timestamp
      @JvmName("getTimestamp")
      get() = _builder.getTimestamp()
      @JvmName("setTimestamp")
      set(value) {
        _builder.setTimestamp(value)
      }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    /**
     * <code>uint64 frame_id = 3;</code>
     */
    public var frameId: kotlin.Long
      @JvmName("getFrameId")
      get() = _builder.getFrameId()
      @JvmName("setFrameId")
      set(value) {
        _builder.setFrameId(value)
      }
    /**
     * <code>uint64 frame_id = 3;</code>
     */
    public fun clearFrameId() {
      _builder.clearFrameId()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class DetectedObjectsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
     */
     public val detectedObjects: com.google.protobuf.kotlin.DslList<struckout.Struckout.DetectedObject, DetectedObjectsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getDetectedObjectsList()
      )
    /**
     * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
     * @param value The detectedObjects to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addDetectedObjects")
    public fun com.google.protobuf.kotlin.DslList<struckout.Struckout.DetectedObject, DetectedObjectsProxy>.add(value: struckout.Struckout.DetectedObject) {
      _builder.addDetectedObjects(value)
    }
    /**
     * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
     * @param value The detectedObjects to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignDetectedObjects")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<struckout.Struckout.DetectedObject, DetectedObjectsProxy>.plusAssign(value: struckout.Struckout.DetectedObject) {
      add(value)
    }
    /**
     * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
     * @param values The detectedObjects to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllDetectedObjects")
    public fun com.google.protobuf.kotlin.DslList<struckout.Struckout.DetectedObject, DetectedObjectsProxy>.addAll(values: kotlin.collections.Iterable<struckout.Struckout.DetectedObject>) {
      _builder.addAllDetectedObjects(values)
    }
    /**
     * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
     * @param values The detectedObjects to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllDetectedObjects")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<struckout.Struckout.DetectedObject, DetectedObjectsProxy>.plusAssign(values: kotlin.collections.Iterable<struckout.Struckout.DetectedObject>) {
      addAll(values)
    }
    /**
     * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
     * @param index The index to set the value at.
     * @param value The detectedObjects to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setDetectedObjects")
    public operator fun com.google.protobuf.kotlin.DslList<struckout.Struckout.DetectedObject, DetectedObjectsProxy>.set(index: kotlin.Int, value: struckout.Struckout.DetectedObject) {
      _builder.setDetectedObjects(index, value)
    }
    /**
     * <code>repeated .struckout.DetectedObject detected_objects = 4;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearDetectedObjects")
    public fun com.google.protobuf.kotlin.DslList<struckout.Struckout.DetectedObject, DetectedObjectsProxy>.clear() {
      _builder.clearDetectedObjects()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun struckout.Struckout.UdpPacket.copy(block: struckout.UdpPacketKt.Dsl.() -> kotlin.Unit): struckout.Struckout.UdpPacket =
  struckout.UdpPacketKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val struckout.Struckout.UdpPacketOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

