[package]
name = "struckout-proto"
version = "0.1.0"
edition.workspace = true

[lib]
path = "lib.rs"

[dependencies]
tonic = { workspace = true }
tonic-prost = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-util"] }
bytes = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
