name: game-master-dev
services:
  app:
    environment:
      - MYSQL_DATABASE=main_dev

  db:
    environment:
      - MYSQL_DATABASE=main_dev
    ports:
      # raとかcargo checkを動かすために公開する
      - 127.0.0.1:3306:3306
