services:
  app:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ../
      dockerfile: ./game_master/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 8020:8020

  db:
    image: mysql:26.7.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 1s

volumes:
  mysql_data:
