unit-test:
    cargo +stable test -p struckout-mcu-core --target x86_64-unknown-linux-gnu
    
[working-directory("crates/app/")]
esp32:
    cargo run --target xtensa-esp32-none-elf --no-default-features --features=esp32,log -p struckout-mcu

[working-directory("crates/app/")]
esp32s3:
    cargo run --target xtensa-esp32s3-none-elf --no-default-features --features=esp32s3,defmt -p struckout-mcu
