alias esp32 := run-esp32
alias esp32s3 := run-esp32s3

target-esp32 := "--target xtensa-esp32-none-elf"
target-esp32s3 := "--target xtensa-esp32s3-none-elf"

features-esp32-app := "--no-default-features --features=esp32,log"
features-esp32s3-app := "--no-default-features --features=esp32s3,defmt"

# Cargo flags needed to build for esp. Same as crates/app/.cargo/config.toml.
esp-flags := "-Zbuild-std=alloc,core"
esp-env-var := "RUSTFLAGS=\"-Clink-args=nostartfiles\"" 


unit-test:
    cargo +stable test -p struckout-mcu-core --target x86_64-unknown-linux-gnu

########## running ##########

[working-directory("crates/app/")]
run-esp32:
    cargo +esp run {{target-esp32}} {{features-esp32-app}} -p struckout-mcu

[default]
[working-directory("crates/app/")]
run-esp32s3:
    cargo +esp run {{target-esp32s3}} {{features-esp32s3-app}} -p struckout-mcu

[working-directory("crates/app/")]
run-esp32-release:
    cargo +esp run {{target-esp32}} {{features-esp32-app}} -p struckout-mcu --release

[working-directory("crates/app/")]
run-esp32s3-release:
    cargo +esp run {{target-esp32s3}} {{features-esp32s3-app}} -p struckout-mcu --release


########## clippy ##########

[working-directory("crates/app/")]
clippy-app-esp32:
    cargo +esp clippy {{target-esp32}} {{features-esp32-app}} -p struckout-mcu

[working-directory("crates/app/")]
clippy-app-esp32s3:
    cargo +esp clippy {{target-esp32s3}} {{features-esp32s3-app}} -p struckout-mcu

clippy-core-esp32:
    {{esp-env-var}} cargo +esp clippy {{target-esp32}} --features=log -p struckout-mcu-core {{esp-flags}}

clippy-core-esp32s3:
    {{esp-env-var}} cargo +esp clippy {{target-esp32s3}} --features=defmt -p struckout-mcu-core {{esp-flags}}
clippy-core-linux:
    cargo +stable clippy --target x86_64-unknown-linux-gnu --no-default-features --features=log,std -p struckout-mcu-core

clippy-all-esp32: clippy-app-esp32 clippy-core-esp32

clippy-all-esp32s3: clippy-app-esp32 clippy-core-esp32s3

clippy-all: clippy-all-esp32 clippy-all-esp32s3
