syntax = "proto3";

package tk75attractions.struckout.v1;

import "google/protobuf/duration.proto";

enum Difficulty {
  DIFFICULTY_UNSPECIFIED = 0;
  DIFFICULTY_NORMAL = 1;
  DIFFICULTY_HARD = 2;
  DIFFICULTY_VERYHARD = 3;
}

message StartGameRequest {
  uint32 machine_id = 1;
  Difficulty difficulty = 2;
  uint32 player_id = 3;
}

message StartGameResponse {
  Event event = 1;
}

message ListenEventsRequest {}

message AddScoreRequest {
  uint32 machine_id = 1;
  uint32 game_id = 2;
  uint32 score_to_add = 3;
}

message AddScoreResponse {}

message AddPlayerRequest {
  string name = 1;
}

message AddPlayerResponse {
  uint32 player_id = 1;
}

message Event {
  message GameStarted {
    Difficulty difficulty = 1;
  }

  message GameTimeLimitNotify {
    google.protobuf.Duration remaining = 1;
  }

  message GameFinished {}

  uint32 machine_id = 1;
  uint32 game_id = 2;

  oneof event_data {
    GameStarted game_started = 3;
    GameTimeLimitNotify game_time_limit_notify = 4;
    GameFinished game_finished = 5;
  }
}

// Service provided by `game_master`.
service GameMasterService {
  rpc AddPlayer(AddPlayerRequest) returns (AddPlayerResponse);

  // Used by `touchpanel`.
  // GameFinishedをtouchpanelが受け取ったらそちらから切断する。
  rpc StartGame(StartGameRequest) returns (stream StartGameResponse);

  // Notify events occured in game_master.
  rpc ListenEvents(ListenEventsRequest) returns (stream Event);

  // Adds score for the game. Used by `projector`.
  rpc AddScore(AddScoreRequest) returns (AddScoreResponse);
}
