import { AboutSlint, VerticalBox } from "std-widgets.slint";
import { TopBar } from "top-bar.slint";
import { StartScreen } from "./screens/start-screen.slint";
import {
    NameInputScreen,
} from "./screens/name-input-screen.slint";
import {
    DifficulitySelectScreen,
} from "./screens/difficulity-select-screen.slint";
import { PlayingScreen } from "./screens/playing-screen.slint";
import { ScoreScreen } from "./screens/score-screen.slint";
import { RankingScreen } from "./screens/ranking-screen.slint";
import { FallbackScreen } from "./screens/fallback-screen.slint";
import {
    ConnectionFailedScreen,
} from "./screens/connection-failed-screen.slint";
import { ConnectingScreen } from "./screens/connecting-screen.slint";

export {
    StartAdopter,
}from "./screens/start-screen.slint";
export {
    NameInputAdopter,
}from "./screens/name-input-screen.slint";
export {
    DifficulitySelectAdopter,
}from "./screens/difficulity-select-screen.slint";
export { FallbackAdopter }from "./screens/fallback-screen.slint";
export {
    ConnectionFailedAdopter,
}from "./screens/connection-failed-screen.slint";
export { PlayingAdopter }from "./screens/playing-screen.slint";
export { ScoreAdopter }from "./screens/score-screen.slint";
export { RankingAdopter }from "./screens/ranking-screen.slint";
export { ConnectingAdopter }from "./screens/connecting-screen.slint";


enum UiNavRoute {
    Start,
    NameInput,
    DifficulitySelect,
    Playing,
    Score,
    Ranking,
    Fallback,
    ConnectionFailed,
    Connecting,
}

export component AppWindow inherits Window {
    full-screen: false;

    in property <UiNavRoute> nav-route;

    VerticalLayout {
        top-bar := TopBar { }

        if nav-route == UiNavRoute.Start: StartScreen { }
        if nav-route == UiNavRoute.NameInput: NameInputScreen { }
        if nav-route == UiNavRoute.DifficulitySelect:DifficulitySelectScreen { }
        if nav-route == UiNavRoute.Playing: PlayingScreen { }
        if nav-route == UiNavRoute.Score: ScoreScreen { }
        if nav-route == UiNavRoute.Ranking: RankingScreen { }
        if nav-route == UiNavRoute.Fallback: FallbackScreen { }
        if nav-route == UiNavRoute.ConnectionFailed: ConnectionFailedScreen { }
        if nav-route == UiNavRoute.Connecting: ConnectingScreen { }
    }
}
