[package]
name = "touchpanel-ui"
version = "0.1.0"
edition.workspace = true

[dependencies]
slint = { workspace = true }
stern = { workspace = true }
struckout-proto = { workspace = true }

strum = { workspace = true }
derive_more = { workspace = true }

[build-dependencies]
slint-build = { workspace = true }
