["game-master:dev"]
shell = "bash -c"
run = "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD_DEV docker compose -f compose.yaml -f compose.dev.yaml up"
dir = "game_master/"
description = "Start a dev server of game-master using docker-compose"
env.MYSQL_ROOT_PASSWORD_DEV = { required = true, redact = true }
raw = true

["game-master:prod"]
run = "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD_PROD docker compose -f compose.yaml -f compose.prod.yaml up"
dir = "game_master/"
description = "Start a production server of game-master using docker-compose"
env.MYSQL_ROOT_PASSWORD_PROD = { required = true, redact = true }
raw = true

["game-master:db"]
run = "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD_DEV docker compose -f compose.yaml -f compose.dev.yaml up db"
dir = "game_master/"
description = "Start a MySQL service for game-master."
env.MYSQL_ROOT_PASSWORD_DEV = { required = true, redact = true }
raw = true

["game-master:build"]
depends = ["patches:disable", "game-master:prepare"]
depends_post = "patches:restore"
run = '''
  FLAGS=""
  if [ ${usage_release:-false} = "true" ]; then
    FLAGS="${FLAGS} --build-arg RELEASE_MODE=true";
    FLAGS="${FLAGS} --build-arg SENTRY_DSN=${SENTRY_DSN}";
  elif [ ${usage_sentry:-false} = "true" ]; then
    FLAGS="${FLAGS} --build-arg SENTRY_DSN=${SENTRY_DSN}";
  fi
  docker compose -f compose.yaml -f compose.dev.yaml build ${FLAGS}
'''
dir = "game_master/"
description = "game-masterのDockerイメージをビルドする"
usage = '''
  flag "--release" help="releaseプロファイルでビルドする"
  flag "--sentry" help="sentryを有効にする (--releaseがついている場合既定で有効)"
'''

["game-master:prepare"]
run = "cargo sqlx prepare -- --all-targets"
dir = "game_master/"
description = "game-masterのクエリ検証用メタデータを生成する"

["game-master"]
run = "docker compose -f compose.yaml -f compose.dev.yaml"
dir = "game_master/"
description = "game-master-devのサービスを操作する"
raw = true
