["game-master:dev"]
run = "docker compose --env-file .env.dev -f compose.yaml -f compose.dev.yaml up"
dir = "game_master/"
description = "Start a dev server of game-master using docker-compose"

["game-master:prod"]
run = "docker compose --env-file .env.prod -f compose.yaml -f compose.prod.yaml up"
dir = "game_master/"
description = "Start a production server of game-master using docker-compose"

["game-master:db"]
run = "docker compose --env-file .env.dev -f compose.yaml -f compose.dev.yaml up db"
dir = "game_master/"
description = "Start a MySQL service for game-master."

["game-master:build"]
depends = ["patches:disable", "game-master:prepare"]
depends_post = "patches:restore"
run = '''
  FLAGS=""
  if [ ${usage_release:-false} = "true" ]; then
    FLAGS="--build-arg RELEASE_MODE=true"
  fi
  docker compose --env-file .env.dev -f compose.yaml -f compose.dev.yaml build ${FLAGS}
'''
dir = "game_master/"
description = "game-masterをビルドする"
usage = '''
  flag "--release" help="releaseプロファイルでビルドする"
'''

["game-master:prepare"]
run = "cargo sqlx prepare -- --all-targets"
dir = "game_master/"
description = "game-masterのクエリ検証用メタデータを生成する"
