name: Android CI

on:
  push: 
    branches: main
    paths: 
      - struckoutCameraApp/**
      - api/proto/**
  pull_request:
    branches: main
    paths:
      - struckoutCameraApp/**
      - api/proto/**
  workflow_dispatch: 

jobs:
  android_ci:
    name: Android CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: struckoutCameraApp/
    steps:
      - uses: actions/checkout@v7
        with:
          sparse-checkout: |
            struckoutCameraApp
            api/proto
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@3f5f9adaf7d9fecd50b5935e54106014257a94e6
      - name: Install protoc
        run: sudo apt install -y protobuf-compiler
      - name: check
        run: ./gradlew :app:check
