name: Nightly Release

on:
  schedule:
    - cron: "0 18 * * *" # UTC 18:00, 03:00 in Japan
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-build:
    strategy:
      matrix:
        os: ["windows-2022", "macos-14", "ubuntu-22.04"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v7
        with:
          sparse-checkout: |
            .cargo
            .mise
            api/proto
            api/rust
            api/spec
            ball_tracker
            game_master
            migrations/mysql
            touchpanel
            xtask
      - uses: Swatinem/rust-cache@f0d9c3887740aee45f6153b24b3a6b815192ec16
      - uses: jdx/mise-action@b90b6cbe247d74ecfb150e2f246c091da4d5174f
        with:
          install_args: protoc
      - name: Install fontconfig for Linux
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libfontconfig1-dev
      - name: Build
        run: SQLX_OFFLINE=true mise exec protoc -- cargo build --release -p ball_tracker -p touchpanel
      
      - name: Upload ball-tracker (Windows)
        uses: actions/upload-artifact@v7
        if: ${{ matrix.os == 'windows-2022' }}
        with:
          name: ball-tracker-x86_64-windows
          path: ./target/release/ball_tracker.exe
      - name: Upload touchpanel (Windows)
        uses: actions/upload-artifact@v7
        if: ${{ matrix.os == 'windows-2022' }}
        with:
          name: touchpanel-x86_64-windows
          path: ./target/release/touchpanel.exe
          
      - name: Upload ball-tracker (macOS)
        uses: actions/upload-artifact@v7
        if: ${{ matrix.os == 'macos-14' }} 
        with:
          name: ball-tracker-aarch64-macos
          path: ./target/release/ball_tracker
      - name: Upload touchpanel (macOS)
        uses: actions/upload-artifact@v7
        if: ${{ matrix.os == 'macos-14' }}
        with:
          name: touchpanel-aarch64-macos
          path: ./target/release/touchpanel

      - name: Upload ball-tracker (Linux)
        uses: actions/upload-artifact@v7
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        with:
          name: ball-tracker-x86_64-linux
          path: ./target/release/ball_tracker
      - name: Upload touchpanel (Linux)
        uses: actions/upload-artifact@v7
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        with:
          name: touchpanel-x86_64-linux
          path: ./target/release/touchpanel
  
  publish-release:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    needs: [rust-build]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          sparse-checkout: .
      - uses: actions/download-artifact@v8
      - name: Remove old release
        # continue even when there's no previous release
        run: gh release delete nightly -y --cleanup-tag || true 
        env: 
          GH_TOKEN: ${{ github.token }}
      - name: Create release
        run: |
          gh release create nightly --notes "nightly release" \
            ${GITHUB_WORKSPACE}/touchpanel-x86_64-linux/touchpanel#touchpanel-x86_64-linux \
            ${GITHUB_WORKSPACE}/ball-tracker-x86_64-linux/ball_tracker#ball-tracker-x86_64-linux \
            ${GITHUB_WORKSPACE}/touchpanel-x86_64-windows/touchpanel.exe#touchpanel-x86_64-windows.exe \
            ${GITHUB_WORKSPACE}/ball-tracker-x86_64-windows/ball_tracker.exe#ball-tracker-x86_64-windows.exe \
            ${GITHUB_WORKSPACE}/touchpanel-aarch64-macos/touchpanel#touchpanel-aarch64-macos \
            ${GITHUB_WORKSPACE}/ball-tracker-aarch64-macos/ball_tracker#ball-tracker-aarch64-macos \
          ||gh release view nightly --json assets --jq '.assets[].name'
        env:
          GH_TOKEN: ${{ github.token }}
