name: Nightly Release

on:
  schedule:
    - cron: "0 18 * * *" # UTC 18:00, 03:00 in Japan
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-build:
    strategy:
      matrix:
        os: ["windows-2022", "macos-14", "ubuntu-22.04"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v7
        with:
          sparse-checkout: |
            .cargo
            .mise
            api/proto
            api/rust
            api/spec
            ball_tracker
            game_master
            migrations/mysql
            touchpanel
            xtask
      - uses: Swatinem/rust-cache@f0d9c3887740aee45f6153b24b3a6b815192ec16
      - uses: jdx/mise-action@b90b6cbe247d74ecfb150e2f246c091da4d5174f
        with:
          install_args: protoc
      - name: Install fontconfig for Linux
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libfontconfig1-dev
      - name: Build
        run: SQLX_OFFLINE=true mise exec protoc -- cargo build --release -p ball_tracker -p touchpanel
      
      - name: Reame binaries
        id: triple
        run: |
          mkdir upload
          case ${{ matrix.os }} in
            "windows-2022")
              echo "triple=x86_64-windows" >> "$GITHUB_OUTPUT"
              mv target/release/ball_tracker.exe upload/ball-tracker-x86_64-windows
              mv target/release/touchpanel.exe upload/touchpanel-x86_64-windows
              ;;
            "macos-14")
              echo "triple=aarch64-macos" >> "$GITHUB_OUTPUT"
              mv target/release/ball_tracker upload/ball-tracker-aarch64-macos
              mv target/release/touchpanel upload/touchpanel-aarch64-macos
              ;;
            "ubuntu-22.04")
              echo "triple=x86_64-linux" >> "$GITHUB_OUTPUT"
              mv target/release/ball_tracker upload/ball-tracker-x86_64-linux
              mv target/release/touchpanel upload/touchpanel-x86_64-linux
              ;;
            *)
              exit 1;;
          esac
      - name: Upload binaries
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: rust-${{ steps.triple.outputs.triple }}
          path: ./upload/

  unity-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target-platform:
          - StandaloneWindows64
          - StandaloneLinux64
          - StandaloneOSX
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          sparse-checkout: |
            projector
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: projector/Library
          key: Library-${{ matrix.target-platform }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ matrix.target-platform }}-
      - uses: game-ci/unity-builder@eb1b9fba120c6e62c9fb7a7a81d6c107ce004c45 # v6.0.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.target-platform }}
          projectPath: projector
      - name: Determine file suffix
        id: triple
        run: |
          case ${{ matrix.target-platform }} in
            "StandaloneWindows64")
              echo "triple=x86_64-windows" >> "$GITHUB_OUTPUT";;
            "StandaloneOSX")
              echo "triple=aarch64-macos" >> "$GITHUB_OUTPUT";;
            "StandaloneLinux64")
              echo "triple=x86_64-linux" >> "$GITHUB_OUTPUT";;
            *)
              exit 1;;
          esac
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: projector-${{ steps.triple.outputs.triple }}
          path: ./build/
  
  publish-release:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'master' }}
    needs: [rust-build, unity-build]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          sparse-checkout: .
      - name: Download projector artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: projector-*
          skip-decompress: true # zipファイルのまま
      - name: Download rust artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: rust-*
      - name: Remove old release
        # continue even when there's no previous release
        run: gh release delete nightly -y --cleanup-tag || true 
        env: 
          GH_TOKEN: ${{ github.token }}
      - name: Create release
        run: |
          gh release create nightly --notes "nightly release" \
            rust-x86_64-windows/* rust-x86_64-linux/* rust-aarch64-macos/* \
            projector-aarch64-macos/projector-aarch64-macos.zip \
            projector-x86_64-windows/projector-x86_64-windows.zip \
            projector-x86_64-linux/projector-x86_64-linux.zip
        env:
          GH_TOKEN: ${{ github.token }}
