name: MCU Build

on:
  push:
    branches:
      - main
    paths:
      - mcu/**
  pull_request:
    paths:
      - mcu/**
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mcu
    strategy:
      fail-fast: false
      matrix:
        action:
          - command: build_esp32
            args: --release --target xtensa-esp32-none-elf --no-default-features --features=esp32,log
          - command: build_esp32s3
            args: --release --target xtensa-esp32s3-none-elf --no-default-features --features=esp32s3,defmt
          - command: fmt
            args: --all -- --check
          - command: clippy
            args: --all-features --workspace -- -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Rust
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          buildtargets: esp32,esp32s3
          ldproxy: false
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Run command
        run: cargo ${{ matrix.action.command }} ${{ matrix.action.args }}
