name: Rust check

on: 
  push:
    branches: main
  pull_request:
    branches: main

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: Swatinem/rust-cache@f0d9c3887740aee45f6153b24b3a6b815192ec16
      - uses: jdx/mise-action@b90b6cbe247d74ecfb150e2f246c091da4d5174f
        with:
          install_args: protoc
      - name: Install fontconfig
        run: |
          sudo apt-get update
          sudo apt-get install -y libfontconfig1-dev
      - name: Run check 
        run:
          mise exec protoc -- SQLX_OFFLINE=true cargo check --all-targets
      - name: Run tests
        run:
          mise exec protoc -- SQLX_OFFLINE=true cargo test
